apiVersion: v1
kind: PersistentVolume
metadata:
  name: wcs-persistent-volume
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: wcs-pd-standard
    fsType: ext4