# Server properties
server:
  # Service context
  contextPath: /water-collection-service
  # Define a custom port instead of the default 8080
  port: 8443
  # SSL properties
  ssl:
    # The path to the keystore containing the certificate
    key-store: classpath:keystore.p12
    # The format used for the keystore
    key-store-type: PKCS12
    # The password used to generate the certificate
    key-store-password: ENC(AvLHc+TwKqOzbakOQX8lxWX9icXXSv5C)
    # The alias mapped to the certificate
    key-alias: wcs

# Encryption properties
jasypt:
  encryptor:
    algorithm: PBEWITHMD5ANDTRIPLEDES
    password: ${JASYPT_ENCRYPTOR_PASSWORD:}

# Tell Spring Security (if used) to require requests over HTTPS
security:
  require-ssl: true

# Security setting for Spring Actuator
management:
  security:
    enabled: true

# Camel properties
camel:
  springboot:
    name: WaterCollectionCamelContext

# Logging config
logging:
#  level:
#    root: DEBUG
  file: /var/log/local/wcs/water-collection-service.log
