# Server properties
server:
  port: 8080
  servlet:
    context-path: /water-collection-service

# Encryption properties
jasypt:
  encryptor:
    algorithm: PBEWITHMD5ANDTRIPLEDES
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

# Security setting for Spring Actuator
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"

# Camel properties
camel:
  springboot:
    name: WaterCollectionCamelContext

ignite:
  persistence:
    enabled: true
    directory: /opt/ignite/pv
  work:
    directory: /opt/ignite/pv/work
