apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-02-18T15:18:20Z
  generation: 1
  labels:
    run: wcs-server
  name: wcs-server
  namespace: default
  resourceVersion: "72948"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/wcs-server
  uid: f3c9a2d6-14be-11e8-aa07-42010a8e018f
spec:
  replicas: 1
  selector:
    matchLabels:
      run: wcs-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: wcs-server
    spec:
      containers:
      - image: gcr.io/wcs-195520/wcs:0.0.1-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: wcs-server
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: 2018-02-18T15:18:20Z
    lastUpdateTime: 2018-02-18T15:18:20Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1